language: c++
compiler: gcc
sudo: required
matrix:
  include:
  # fully specify builds, include can't dynamically expand matrix entries
  # relative order of sudo and env is important so that addons: is recognized

# Linux 64bit, OF master
  - os: linux
    dist: trusty
    sudo: required
    env: TARGET="linux64" OF_BRANCH="master"
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-4.9
          - g++-4.9
          - gdb

# OSX, OF master
  - os: osx
    osx_image: xcode9
    compiler: clang
    env: TARGET="osx" OF_BRANCH="master"


  # Exclude the default build that would otherwise be generated
  # see https://github.com/travis-ci/travis-ci/issues/1228
  exclude:
    - compiler: gcc

before_install:
  - curl -SLsO https://raw.githubusercontent.com/bakercp/ofxAddonScripts/${OF_BRANCH}/scripts/ci/tools/install.sh
  - source install.sh
install:
  - cd ~
  - git clone --depth=${OF_CLONE_DEPTH} --branch=${OF_CLONE_BRANCH} https://github.com/${OF_CLONE_USERNAME}/openFrameworks
  - cd openFrameworks
  - scripts/ci/addons/install.sh
  - clone_addons $(get_all_dependencies_for_addon ${THIS_ADDON_DIR})
script:
  - scripts/ci/addons/build.sh
git:
  depth: 10
